languageCode = "en-us"
title = "Ecology, Society, Democracy"
theme = "ananke"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
disableKinds = ["taxonomy","taxonomyTerm"]

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
    description = "Growing my understanding of democratic ecosocialism"
    twitter = "https://twitter.com/BradVenner"
    instagram = ""
    youtube = ""
    github = "https://github.com/bvenner"
    gitlab = ""
    linkedin = ""
    mastodon = ""
    slack = ""
    stackoverflow = ""
    # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
    background_color_class = "bg-black"
    featured_image = "static/images/arisbe.jpg"
    recent_posts_number = 6
