---
title: Ecosocialism Theory Outline
author: Brad Venner
date: '2019-02-11'
slug: ecosocialism-theory-outline
categories: []
tags: []
---

# What Is Ecosocialism

For the ecosocialist, the cause of climate change is capitalism, and the cure for climate change is socialism.

## Marxist perspective of nature, natural resources and the contradictions of extractive capitalism

> it is not the unity of living and active humanity with the natural, inorganic condi-
tions of their metabolic exchange with nature, and hence their appropriation of
nature, which requires explanation or is the result of a historic process, but rather
the separation between these inorganic conditions of human existence and this
active existence, a separation which is completely posited only in the relation of
wage labor and capital. (Marx, Gundrisse, p. 489)

> The private property of particular individuals in the earth will appear just as absurd
as the private property of one man in other men. Even an entire society, a nation, or
all simultaneously existing societies taken together, are not owners of the earth.
They are simply its possessors, its beneficiaries, and have to bequeath it in an
improved state to succeeding generations as boni patres familias [good heads of
the household]. (Marx, Capital, Vol. 3, p. 911)


## Development of ‘ecosocialism’ and reflection on the positions of Marx and Engels
## 1st - 3rd “waves” of ecosocialist thought
## Conflicts with other environmentalist and ‘leftist’ traditions

### 

## Most recent ecosocialist thoughts on climate change

### An Ecological Revolution

Bellamy Foster 

