---
title: Thoughts-on-democratic-inquiry-into-democracy
author: Bradley Venner
date: '2019-10-23'
slug: thoughts-on-democratic-inquiry-into-democracy
categories: [pragmatic-ecosocialism]
tags: []
---

The fiercevulnerabilty workshop reminded me that a peer-based education approach to democracy is necessary (and could be interesting).  I'd like such a workship to combine some recent thoughts, such as the 'curriculum project' that Marie and I were talking about, my idea to start a working group on democracy within DSA, teaching a course on pragmatic ecosocialism (with an emphasis on how pragmatism could unite democratic socialism and scientific socialism), my discussion with Nick about whether Extinction Rebellion was anarchist or democratic, our discussions about having another weekly soup night event, and the weekly meditation group that Kritee is doing in Boulder.

My first iteration on the title was a democratic dialogue on democracy, since I was thinking about a Bohmian dialogue.  But inquiry is a better word, as I'm willing to try more goal directed approaches than Bohm's approach.  Plus, a first iteration of topics might be democractic education.  Inquiry also potentially points to the unification of theory and practice that I believe would be the goal of such a group.  The reflective title is also intended to point to such a unfication, as democratic methods are applied to understand democratic theory.

One way to start the group would be to view Astra Taylor's movie 'What is Democracy'.  This could be done in 30 minute segments over three meetings.  

There are so many modifiers that have been used with 'democratic', 'democratize', or 'democracy'.  A good exercise might be to have participants list such instances.  For example:

1.  Economic democracy
2.  Social democracy
3.  Democratic socialism
4.  Democratic education
5.  Education for democracy
6.  Energy democracy
7.  Democratic workplace
8.  Democratic governance
9.  Participatory democracy
10.  Democratic elections
