---
title: Thoughts on an Energy Democracy Workshop
author: Bradley Venner
date: '2020-11-24'
slug: thoughts-energy-democracy-theory
---

## Existing energy democracy framework - process, goal, outcome

## Aristotle three forms of knowledge - techne, phronesis, episteme 

## Poinsot's three classes of signs - natural, conventional, stipulated

## Gare's three dialectics - labor, recognition, representation

These three dialectics correspond in a way with Poinsot's division of signs into natural, conventional and stipulated.  

It strikes me that the three dialectics are the ways that culture is transmitted.  Culture is transmitted through the built environment and our various artifacts (second nature).  Culture is also transmitted through habits, imitation of what other people are doing.  Culture is also transmitted through language.

## Gare - (natural) ecology, human ecology, political ecology.


## Frega's three democratic principles - relational parity, inclusive authority, social involvement.  

Note that these are all social principles and don't seem to generalize to a more material/energy framework.

## Hornborg's nature, social, justice.  

Hornborg emphasizes the limitations of 'general-purpose' money and places it at the center of the logic of capitalism.  I contend that there are more resources in semiotics to develop an alternative logic than used by Hornborg.  Peirce developed semiotics as logic, although likely without anti-capitalism as its intended purpose.  

Hornborg develops the notion that 'unequal' resource flows are central to capitalism.  Money is used to obscure this inequality, to give it a veneer of justice.  The logic of money, as developed by neoclassical economists, is not connected with material and energy flows.

Since a key part of energy democracy is the development of renewable energy, the emphasis on 'equal exchange' of energy seems odd.  The ecological analysis would be that ecology takes place far from equilibrium, as an open system that relies upon energy from the sun to maintain this position.  Hornborg relies upon the profound skepticism around renewables that was fashionable on the left (e.g. Planet of the Humans), but doesn't seem grounded in an analysis of matter and energy flows.  But I like the idea that we need to ensure that matter flows are sustainable.  

Colin dropped a line of 'lets invade Bolivia to get their lithium' yesterday, drawing the skeptical analogy between fossil energy and energy storage.  This analogy seems to mistake the material and energy flows required in the fossil energy system, where they are used as inputs, for a system where matter is used more as a 'means of production'.  But it does point to
