---
title: Thoughts on Semiotics, Social Intelligence, and Democracy
author: Bradley Venner
date: '2021-08-14'
slug: thoughts-semiotics-social-intelligence-democracy
---

I spent the morning changing the name of this blog and repository to *Ecology, Society, Democracy* from *Ecology, Society, Semiotics*. My main reason for the change is my growing identification of myself as a democratic ecosocialist and my thought that. The former title was influenced by Locke's definition of semiotics as the third branch of science, along with what would now be 'natural science' and something like 'social science', which Locke defined as

>  that which man himself ought to do, as a rational and voluntary agent, for the attainment of any end, especially happiness.

But the name change also shows the influence of a couple years of reading Dewey and increasingly understanding his philosophy as fundamentally Peircean, but moving towards a more distributed, pluralistic understanding of Peirce. Dewey places democracy as a central concept in his philosophy, understood as 'social intelligence' (as he calls it in Human Nature and Conduct). 